- name: stop NGINX
  become: yes
  become_user: root
  shell: service nginx stop
  args:
    warn: false

- name: make sure snap core is installed
  become: yes
  become_user: root
  community.general.snap:
    name: core

- name: make sure snap core is up to date
  become: yes
  become_user: root
  command: snap refresh core

- name: remove old certbot-auto install
  become: yes
  become_user: root
  file:
    path: /home/{{ deploy_user }}/certbot-auto
    state: absent

- name: install certbot from snap
  become: yes
  become_user: root
  community.general.snap:
    name: certbot
    classic: yes

- name: prepare the certbot command
  become: yes
  become_user: root
  file:
    dest: /usr/bin/certbot
    state: link
    src: /snap/bin/certbot

- name: generate certs
  become: yes
  become_user: root
  shell: "certbot certonly --standalone -d {{ letsencrypt_domain }} --email {{ letsencrypt_email}} --non-interactive --agree-tos"

- name: install nginx config
  template:
    src: ./templates/le_nginx_template.server
    dest: /etc/nginx/sites-available/nginx-{{ rails_env }}.server

- name: enable nginx config
  file:
    dest: /etc/nginx/sites-enabled/nginx-{{ rails_env }}.server
    state: link
    src: /etc/nginx/sites-available/nginx-{{ rails_env }}.server

- name: create cron job to auto renew
  become: yes
  become_user: root
  cron:
    name: "certbot auto-renew"
    minute: "20"
    hour: "6"
    job: "certbot renew --nginx --quiet"

- name: start NGINX
  become: yes
  become_user: root
  shell: service nginx start
  args:
    warn: false