- name: Monit | Copy monitrc template
  template: src=templates/monitrc dest=/etc/monit/monitrc owner=root group=root
  become: yes

- name: Open port 2812 for monit
  command: ufw allow 2812
  become: yes

- name: Monit | Copy file system monitoring conf.d template
  template: src=templates/monit_filesystem.d dest=/etc/monit/conf.d/filesystem.d owner=root group=root
  become: yes

- name: Monit | Copy server monitoring conf.d template
  template: src=templates/monit_server.d dest=/etc/monit/conf.d/server.d owner=root group=root
  become: yes

- name: Monit | Copy nginx conf.d template
  template: src=templates/monit_nginx.d dest=/etc/monit/conf.d/nginx.d owner=root group=root
  become: yes

- name: Monit | postgresql Copy conf.d template
  template: src=templates/monit_postgresql.d dest=/etc/monit/conf.d/postgresql.d owner=root group=root
  become: yes

- name: Monit | Copy puma conf.d template
  template: src=templates/monit_puma.d dest=/etc/monit/conf.d/puma.d owner=root group=root
  become: yes

- name: Monit | Copy sidekiq conf.d template
  template: src=templates/monit_sidekiq.d dest=/etc/monit/conf.d/sidekiq.d owner=root group=root
  become: yes

- name: Monit Reload
  command: monit reload
  become: yes

- name: Monit Restart
  command: monit restart all
  become: yes
