- name: apt-update
  apt:
    update_cache: true

- name: add deploy user
  user:
    name: "{{ deploy_user }}"
    shell: /bin/bash
    password: "{{ deploy_user_password }}"
    ssh_key_file: .ssh/id_rsa

- name: add {{deploy_user}} sudoers file
  template: src=./templates/sudoers_user dest=/etc/sudoers.d/{{deploy_user}} mode=0440

- name: Set includedir in sudoers
  lineinfile:
    dest: /etc/sudoers
    line: "#includedir /etc/sudoers.d"
    state: present
    validate: "/usr/sbin/visudo -cf %s"

- name: install packages
  become: yes
  apt:
    update_cache: true
    pkg: ['curl', 'build-essential', 'libssl-dev', 'libpq-dev', 'libreadline-dev', 'zlib1g-dev', 'python3-pip', 'git-core', 'python3-pycurl', 'libcurl4-openssl-dev', 'ufw', 'fail2ban', 'libyaml-dev', 'libxml2-dev', 'libxslt1-dev', 'acl']

- name: install psycopg2
  pip:
    name: psycopg2

- name: set hostname
  hostname:
    name: "{{ hostname }}"
