- name: apt-update
  apt:
    update_cache: true

- name: add deploy user
  user:
    name: "{{ deploy_user }}"
    shell: /bin/bash
    password: "{{ deploy_user_password }}"
    ssh_key_file: .ssh/id_rsa

- name: Add user to sudoers file
  lineinfile:
    path: /etc/sudoers
    regexp: '^{{deploy_user}}'
    line: '{{deploy_user}} ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: install packages
  become: true
  apt:
    update_cache: true
    pkg:
      - curl
      - build-essential
      - libssl-dev
      - libpq-dev
      - libreadline-dev
      - zlib1g-dev
      - python3-pip
      - git-core
      - python3-psycopg2
      - python3-pycurl
      - libcurl4-openssl-dev
      - ufw
      - fail2ban
      - libyaml-dev
      - libxml2-dev
      - libxslt1-dev
      - acl

- name: set hostname
  hostname:
    name: "{{ hostname }}"
