- name: Sidekiq | Copy systemd template to systemd multiuser directory
  template: src=templates/sidekiq.service dest=/etc/systemd/system/sidekiq.service owner=root group=root
  become: yes

- name: systemctl daemon-reload
  command: systemctl daemon-reload
  become: yes

- name: configure sidekiq to restart on reboot
  command: systemctl enable sidekiq
  become: yes

# - name: explicitly start sidekiq
#   command: systemctl start sidekiq
#   become: yes

- name: add sudoers file to allow passwordless restarts
  template: src=./templates/sudoers_sidekiq dest=/etc/sudoers.d/sidekiq

- name: Set includedir in sudoers
  lineinfile:
    dest: /etc/sudoers
    line: "#includedir /etc/sudoers.d"
    state: present
    validate: "/usr/sbin/visudo -cf %s"
